config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  root to: 'pages#home'
  resources :food_tours do
    resources :bookings, only: [ :create, :update ]
    resources :reviews, only: [ :create, :update ]
  end
  resources :bookings, only: [ :edit, :destroy ]


  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :food_tour
end

app/models/food_tour.rb
class FoodTour < ApplicationRecord
  include PgSearch
  pg_search_scope :tour_search, against: [ :city, :country]

  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user

  mount_uploader :photo, PhotoUploader
  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  def average_rating
    if self.reviews.count > 0
      total = 0
      self.reviews.each do |review|
        total += review.rating
      end
      return total / self.reviews.count
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food_tour
  validates :content, length: { minimum: 20 }
  validates :rating, inclusion: 0..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :bookings
  has_many :food_tours
  mount_uploader :avatar, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_food_tour, only: [ :create ]

  def edit
   @booking = Booking.find(params[:id])
   @food_tour = @booking.food_tour
   authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to dashboard_path, notice: 'Successfully Updated!'
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path, notice: 'Done!'
  end

  def create
     @booking = Booking.new(booking_params)
     @booking.user = current_user
     @booking.food_tour = @food_tour
     if @booking.save
      authorize @booking
      # redirect_to dashboard_path
    else
      render 'new'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end

  def set_food_tour
    @food_tour = FoodTour.find(params[:food_tour_id])
  end

end

app/controllers/food_tours_controller.rb
class FoodToursController < ApplicationController
  before_action :set_food_tour, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # return redirect_to roo_path if current.age < 18
    if params[:q]
      @food_tours = policy_scope(FoodTour).where("city iLIKE '%#{params[:q]}%' OR location iLIKE '%#{params[:q]}%'")
    else
      @food_tours = policy_scope(FoodTour)
    end
    @hash = Gmaps4rails.build_markers(@food_tours) do |food_tour, marker|
      marker.lat food_tour.latitude
      marker.lng food_tour.longitude
    end
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
  end

  def show
    @booking = Booking.new
    @review = Review.new
    @food_tour_coordinates = { lat: @food_tour.latitude, lng: @food_tour.longitude }
    authorize @food_tour
    @hash = Gmaps4rails.build_markers(@food_tour) do |food_tour, marker|
      marker.lat food_tour.latitude
      marker.lng food_tour.longitude
    end
  end

  def new
    @food_tour = FoodTour.new
    authorize @food_tour
  end

  def create
    dates = {}
    match_data = params[:dates].match(/([)\d\-]+) to ([\d\-]+)/)
    dates[:start_date] = match_data[1]
    dates[:end_date] = match_data[2]

    @food_tour = FoodTour.new(food_tour_params.merge(dates))
    @food_tour.user_id = current_user.id
    authorize @food_tour
    if @food_tour.save
      redirect_to food_tour_path(@food_tour)
    else
      render 'new'
    end
  end

  def update
    authorize @food_tour
    @food_tour.update(food_tour_params)
    redirect_to food_tour_path
  end

  def edit
    authorize @food_tour
  end

  def destroy
    authorize @food_tour
    @food_tour.destroy
    redirect_to dashboard_path, notice: "Done!"
    # redirect_to request.referer.include?('food_tours')
  end

  private

  def set_food_tour
    @food_tour = FoodTour.find(params[:id])
  end

  def food_tour_params
    params.require(:food_tour).permit(:title, :description, :city, :price, :cuisine, :capacity, :location, :photo, :photo_cache, :search)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :dashboard]
  def home
    @food_tours = FoodTour.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@food_tours) do |food_tour, marker|
      marker.lat food_tour.latitude
      marker.lng food_tour.longitude
    end
  end

  def dashboard
    @user = current_user
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar, :avatar_cache)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @food_tour = FoodTour.find(params[:food_tour_id])
    @review = Review.new(review_params)
    @review.food_tour = @food_tour
    @review.save

    authorize @review
  end


private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form_booking.html.erb
<%= simple_form_for [@food_tour, @booking] do |f| %>
    <%= f.input :date, as: :string, label: false, required: false, input_html: {class: "datepicker form-inline"} %>
    <%= f.button :submit, id: 'sweet-alert-demo', class: 'btn btn-primary' %>
<% end %>

<input type="hidden" value="<%= @food_tour.start_date %>" id="foodTourStartDate">
<input type="hidden" value="<%= @food_tour.end_date %>" id="foodTourEndDate">

app/views/bookings/edit.html.erb
<div class="text-center">
  <h1>Select a new date</h1>
</div>

<div class="container text-center">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
      <%= render 'form_booking' %>
    </div>
  </div>
</div>

app/views/food_tours/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 text-center">
      <h1>New Food Tour</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
      <%= simple_form_for @food_tour do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :city %>
        <%= f.input :location %>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <div class="form-group integer optional food_tour_capacity">
          <label class="control-label integer optional" for="dates">Availability Dates</label>
          <%= text_field_tag :dates, nil, class: 'datepicker-range' %>
        </div>
        <%= f.input :cuisine %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/food_tours/edit.html.erb
<%= render 'form' %>

app/views/food_tours/index.html.erb
<div class="container">
  <div class="row">
    <% @food_tours.each do |food_tour| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <%= link_to food_tour_path(food_tour) do %>
          <div class="card card-link" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( '<%= cl_image_path(food_tour.photo? ? food_tour.photo : 'fysedljjycu4kwcqsasb') %>' );">
              <h1 class="text-center"><%= food_tour.title %></h1>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/food_tours/new.html.erb
 <%= render 'form' %>

app/views/food_tours/show.html.erb
<% content_for(:title, @food_tour.title) %>

<div class="flex-container">
  <div class="flex-item bg-cover relative" style="background-image: url(<%= cl_image_path @food_tour.photo? ? @food_tour.photo : 'fysedljjycu4kwcqsasb' %>)">
  <%= image_tag @food_tour.user.avatar, class:'avatar-large top-right' %>
  </div>

  <div class="flex-item">
    <div class="center-list">
      <h3 class="text-center"><%= @food_tour.title %></h3>
      <div class="row">
        <div class="col-xs-6"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= @food_tour.city %></div>
        <div class="col-xs-6"><i class="fa fa-usd" aria-hidden="true"></i> <%= @food_tour.price %></div>
        <div class="col-xs-6"><i class="fa fa-cutlery" aria-hidden="true"></i> <%= @food_tour.cuisine %></div>
        <div class="col-xs-6"><i class="fa fa-calendar" aria-hidden="true"></i> Start: <%= @food_tour.start_date %></div>

        <div class="col-xs-6">
          <% if policy(@food_tour).edit? %>
            <%= link_to edit_food_tour_path(@food_tour) do %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
            <%= link_to food_tour_path, method: :delete, data: { confirm: 'Are you sure?'} do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>
        <div class="col-xs-6"><i class="fa fa-calendar" aria-hidden="true"></i> End: <%= @food_tour.end_date %>
        </div>
      </div>
      <div class="row">
        <% if current_user != @food_tour.user || !user_signed_in? %>
          <div class="form-inline text-center">
            <%= render 'bookings/form_booking' %>
          </div>
        <% end %>
      </div>
      <hr>
      <p><%= @food_tour.description %></p>
      <hr>
        <% if !@food_tour.bookings.blank? %>
          <% @food_tour.bookings.each do |booking| %>
            <%= image_tag (booking.user.avatar), class: "avatar" %>
          <% end %>
        <% else %>
            <p> No attendees at the moment </p>
        <% end %>
    </div>
  </div>

  <script>
  function bindSweetAlertButtonDemo() {
    document.getElementById('sweet-alert-demo').addEventListener('click', () => {
      swal({
        title: "Awesome!",
        text: "Congrats, food tour booked!",
        icon: "success"
      })
    });
  }
  bindSweetAlertButtonDemo();
  let createBtn = document.getElementById('sweet-alert-demo')
  createBtn.addEventListener('click', () => {
    document.body.addEventListener('click', () => {
      window.location.href = "http://localhost:3000/dashboard";
    })
  })
  </script>
</div>

<div class="flex-container">

  <div class="flex-items padded" style="width: 50%; height: 45vh">
    <div id="reviews">
      <h2 id="review-count"><%= pluralize @food_tour.reviews.size, "review" %></h2>
      <% if @food_tour.reviews.blank? %>
        Be the first to leave a review for <%= @food_tour.title %>
      <% else %>
        <% @food_tour.reviews.each do |review| %>
          <%= render 'reviews/show_review', review: review %>
        <% end %>
      <% end %>
    </div>
    <%= render 'reviews/form_review', food_tour: @food_tour, review: @review %>
  </div>


  <div class="flex-item">
    <div id="map-show" style="width: 100%; height: 45vh;"></div>
  </div>

</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map-show' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  <% end %>
<% end %>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_food_tour_form.html.erb
<!-- form form food_tour -->

<%= simple_form_for @food_tour do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :city %>
  <%= f.input :price %>
  <%= f.input :dates %>
  <%= f.input :cuisine %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Devour food tours <i class="fa fa-copyright"></i>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "cooking.svg", class: "" %>
  </a>

  <% unless params[:controller] == 'pages' && params[:action] == 'home' %>
    <%= form_tag(food_tours_path, method: :get, :class => 'form-inline text-center') do %>
      <%= text_field_tag :q, nil, class: 'form-control navb' %>
       <%= button_tag(type: "submit", class: "btn btn-default navbar-search") do %>
        <i class="fa fa-search"></i>
    <% end %>
    <% end %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <a href="/dashboard" class="navbar-wagon-item navbar-wagon-link">Dashboard</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% avatar_url = current_user.avatar? ? current_user.avatar : "user.png" %>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: { toggle: 'dropdown' } %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="/dashboard">Dashboard</a></li>
          <li><a href="/food_tours/new">Add a foodtour</a></li>
          <li><a href="/users/edit">Edit profile</a></li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'log-out' %>
        </ul>
      </div>
    </div>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary sign-in' %>
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary sign-up' %>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all'%>
  </head>
  <body>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flashes' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<% content_for(:title, @user.first_name) %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12 offset-md-1">
      <h1> Your Dashboard </h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12 offset-md-1">
      <h3>Tours I've Booked</h3>
      <% @user.bookings.each do |booking| %>
          <div class="product">
            <%= cl_image_tag booking.food_tour.photo, class:"product-image hidden-xs" %>
            <div class='product-body'>
              <h3><%= booking.food_tour.title %></h3>
              <p><%= booking.food_tour.description %></p>
            </div>
            <ul class="list-inline product-controls hidden-sm hidden-xs">
              <li><%= booking.date %></li>
              <li><%= booking.food_tour.price %></li>
              <li><i class="fa fa-usd" aria-hidden="true"></i></li>
              <li><%= link_to edit_booking_path(booking) do %>
                <i class="fa fa-pencil" aria-hidden="true"></i>
              <% end %></li>
              <li><%= link_to booking_path(booking), method: :delete, data: { confirm: 'Are you sure?'} do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %></li>
            </ul>
            <%= link_to '', food_tour_path(booking.food_tour), class: 'food-card-link' %>
          </div>
      <% end %>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-lg-12 offset-lg-1">
      <h3>Tours I'm Running</h3>

      <% @user.food_tours.each do |food_tour| %>
        <div class="product">
          <%= cl_image_tag food_tour.photo, class:"product-image hidden-xs" %>
          <div class='product-body'>
            <h3><%= food_tour.title %></h3>
            <p><%= food_tour.description %></p>
            <% if !food_tour.bookings.blank? %>
              Number of booked attendees: <%= food_tour.bookings.count %>
            <% else %>
              <p> No attendees at the moment </p>
            <% end %>
          </div>

          <ul class="list-inline product-controls hidden-sm hidden-xs">
            <li><%= food_tour.start_date.strftime("%d/%m/%Y")  %></li> to
            <li><%= food_tour.end_date.strftime("%d/%m/%Y") %></li> -
            <li><%= food_tour.price %></li>
            <li><i class="fa fa-usd" aria-hidden="true"></i></li>
            <li><%= link_to edit_food_tour_path(food_tour) do %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %></li>
            <li><%= link_to food_tour_path(food_tour), method: :delete, data: { confirm: 'Are you sure?'} do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %></li>
          </ul>
          <%= link_to '', food_tour_path(food_tour), class: 'food-card-link' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for(:title, "Devour Food tour") %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1488743196279-d2b91fd9e633?auto=format&fit=crop&w=1400');">
  <div class="banner-content">
    <h1>Welcome to Devour food tours</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <%= form_tag(food_tours_path, method: :get, :class => 'form-inline') do %>
      <%= text_field_tag :q, nil, class: 'form-control search-style', placeholder: 'Search by city or country...' %>
      <%= button_tag(type: "submit", class: "btn btn-primary search-button") do %>
        <i class="fa fa-search"></i>
    <% end %>
    <% end %>
    <!-- <a class="btn btn-primary btn-lg">Start now</a> -->
  </div>
</div>

<br>

<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    var styles = [
                {
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "water",
                    "stylers": [
                        {
                            "visibility": "on"
                        },
                        {
                            "color": "#2f343b"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "stylers": [
                        {
                            "visibility": "on"
                        },
                        {
                            "color": "#404E61"
                        }
                    ]
                },
                {
                    "featureType": "administrative",
                    "elementType": "geometry.stroke",
                    "stylers": [
                        {
                            "visibility": "on"
                        },
                        {
                            "color": "#2f343b"
                        },
                        {
                            "weight": 1
                        }
                    ]
                }
            ]
    var handler = Gmaps.build('Google');
    handler.buildMap({
        provider: {
        styles: styles
        // pass in other Google Maps API options here
        // => https://developers.google.com/maps/documentation/javascript/reference#MapOptions
      }, internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  <% end %>
<% end %>

<div class="text-center">
  <h2>Get inspired....</h2>
</div>


<div class="container">
  <div class="row">
    <% @food_tours.each do |food_tour| %>
      <div class="col-xs-12 col-sm-6 col-lg-4">
        <%= link_to food_tour_path(food_tour) do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( '<%= cl_image_path(food_tour.photo? ? food_tour.photo : 'fysedljjycu4kwcqsasb') %>' );">
              <h1 class="text-center"><%= food_tour.title %></h1>
               <div>
                 <%= cl_image_tag food_tour.user.avatar, class: 'card-av' %>
               </div>
              <div class="stars">
                <% if !food_tour.average_rating.nil? %>
                  <% food_tour.average_rating.times do %>
                    <i class="fa fa-star" aria-hidden="true"></i>
                  <% end %>

                  <% (5 - food_tour.average_rating).times do %>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                  <% end %>
                  <% else %>
                  <p>No reviews</p>
                <% end %>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


<!-- then list the food_tours in cards-->

app/views/reviews/_form_review.html.erb
<%= simple_form_for([ food_tour, review ], remote: true) do |form| %>
  <%= form.input :rating, collection: 0..5 %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show_review.html.erb
<p><%= review.content %></p>

<% review.rating.times do %>
  <i class="fa fa-star" aria-hidden="true"></i>
<% end %>

<% (5 - review.rating).times do %>
  <i class="fa fa-star-o" aria-hidden="true"></i>
<% end %>

app/views/reviews/create.js.erb
var addBooking = document.getElementById('new_reviews')
var reviewForm = document.getElementById('new_review')

<% if @review.persisted? %>
// 1. create the html for the review
var newReview = "<%= j render 'reviews/show_review', review: @review %>";
// 2. append the new review to the list
var reviews = document.getElementById('reviews');
reviews.insertAdjacentHTML('beforeend', newReview);
// 3. empty out the input box
reviewForm.innerHTML = "<%= j render 'reviews/form_review', food_tour: @food_tour, review: Review.new %>";
var count = document.getElementById('review-count');
count.empty();
count.text('<%= pluralize @food_tour.reviews.size, "review" %>');
<% else %>
// 1. rerender the form partial with the new @review
reviewForm.innerHTML = "<%= j render 'reviews/form_review', food_tour: @food_tour, review: @review %>";
<% end %>